
package com.SafeStreets.Client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Dispatcher", targetNamespace = "http://SafeStreets.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Dispatcher {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "UserRegistration")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "UserRegistration", targetNamespace = "http://SafeStreets.com/", className = "com.SafeStreets.Client.UserRegistration")
    @ResponseWrapper(localName = "UserRegistrationResponse", targetNamespace = "http://SafeStreets.com/", className = "com.SafeStreets.Client.UserRegistrationResponse")
    @Action(input = "http://SafeStreets.com/Dispatcher/UserRegistrationRequest", output = "http://SafeStreets.com/Dispatcher/UserRegistrationResponse")
    public Boolean userRegistration(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
