package com.SafeStreets.model;

public enum ViolationType {
    PARKING_ON_BIKE_LANES,
    PARKING_ON_RESERVED_STALL,
    DOUBLE_PARKING,
    PARKING_ON_PEDESTRIAN_CROSSING,
    PARKING_ON_SIDEWALK,
    PARKING_ON_TRAFFIC_ISLAND,
    PARKING_NOT_PAYED,
    PARKING_ON_RED_ZONE,
    TRAFFIC_LIGHT_VIOLATION,
    INCIDENT_VEHICLES_VIOLATION,
    SPEED_VIOLATION,
    AGAINST_TRAFFIC_VIOLATION,
    OTHER_VIOLATION;

}
